### ISSUE TITLE
Automatic Launcher Detection

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartSim#111]
# Description
Automatically detect the launcher to use with a default ``auto`` argument. 

# Justification
Some of the recent portability issues have spurred the interest in having more of the driver scripts be portable across system/launcher types. In the first few versions of SmartSim, there were not enough launcher and run settings types implementations to necessitate that such portability features, however, there are many now.

# Implementation Strategy
ex.

```python
from smartsim import Experiment

exp = Experiment(name="test", launcher="auto")
```

This detection algorithm will also spot necessary dependencies for each WLM. For example, the Slurm launcher necessitates that ``sacct`` be available. We can check for ``sacct`` if the launcher detection function returns slurm.

## acceptance Criteria

- [x] Experiment should have new ability to take ``auto`` as an arugment for launcher and automatically detect the workload manager of the system.
- [x] Must have a reliable way to test this for all WLM even when not on a system with any WLM.
- [x] Test manually on multiple different internal systems.
- [x] Be able to handle the case where many workload managers are present on a system.

**Comment by al-rigazzi** [comment]
The mechanism has been tested on the following systems:
- Horizon (Slurm)
- Macbook (Local)
- Swan (PBS)
- Theta (Cobalt)
- Summit (LSF)

The order in which they are tested is:
- LSF, PBS, Cobalt, Slurm; fallback Local
Slurm is at the end of the list, because it sometimes co-exists with other launchers, but it is unlikely people want it in that case (e.g. on Summit there is Slurm, but it is never mentioned in the docs).
