### ISSUE TITLE
Compile with NVIDIA HPC SDK or link to NVIDIA-compiled apps

### ISSUE THREAD

**Issue by b-fg** [CrayLabs/SmartSim#286]
In my research group, we have a CFD Fortran solver for GPUs, [Sod2D](https://gitlab.com/LucasBSC21387/sod2d_gitlab). To compile and run Sod2D we use compilers from the NVIDIA HPC suite. Since we want to use SmartSim to provide communication between Sod2D and ML models written in Python, I wanted to ask which is the best way to do so. Ideally, we would like to run Sod2D on GPUs, while the ML model runs on CPUs. We have tried to compile SmartSim on the GPU cluster using the NVIDIA compilers without success. So here are a few related questions:

- Should it be possible to compile SmartSim with NVIDIA compilers?
- Can GCC-compiled SmartSim talk to a NVIDIA HPC-compiled app?
- What would be the best way to make this work?

Thanks in advance, and thanks for the library! :)

**Comment by ashao** [comment]
That's an interesting deployment strategy; you'll definitely want to look into the intra-op and interop-threads when you make the `Orchestrator`since that maps onto the parallelization on CPUs.

To answer your question, no Nvidia's compilers are not supported at this time, while I think (I'd have to double check) we can compile the C and C++ clients with them, the Nvidia Fortran compiler only has partial support for up to Fortran 2008, while we use some of Fortran 2018's object oriented features. At some point they're moving the Fortran compiler to LLVM and will at that point have full Fortran2018 support.

As far as your other questions:

_Can GCC-compiled SmartSim talk to a Nvidia HPC-compiled app?_
We haven't tried this, but I think it should work. You might have to futz with some compiler flags to get object names correct. We have (and do) cross-compile with Intel and GCC just fine.

_What would be the best way to make this work?_
I'd say compile the SmartRedis library with the following:
```
export CC=/path/to/gcc CXX=/path/to/g++ FC=/path/to/gfortran
make lib-with-fortran
```

I see you use CMake to build Sod2D, so you can adapt your `CMakeLists.txt` based on the following: https://www.craylabs.org/docs/installation_instructions/basic.html?highlight=cmake#linking-instructions-for-cmake-based-build-systems

Feel free to keep this issue open or contact me at Andrew.Shao@hpe.com if you want to try to figure this out together.

**Comment by b-fg** [comment]
> That's an interesting deployment strategy; you'll definitely want to look into the intra-op and interop-threads when you make the Orchestratorsince that maps onto the parallelization on CPUs.

Alright, thanks for the info, and noted about the Nvidia Fortran compiler support.

> We haven't tried this, but I think it should work. You might have to futz with some compiler flags to get object names correct. We have (and do) cross-compile with Intel and GCC just fine.

Ok, this is good to know, thank you! We should try this approach then.

I have already [linked](https://gitlab.com/LucasBSC21387/sod2d_gitlab/-/blob/smartsim/cmake/smartredis.cmake) SmartRedis with Sod2D in the [smartsim branch](https://gitlab.com/LucasBSC21387/sod2d_gitlab/-/tree/smartsim?ref_type=heads) of Sod2D, where I will keep development of this feature for the moment. The SmartRedis module can be found [here](https://gitlab.com/LucasBSC21387/sod2d_gitlab/-/blob/smartsim/src/lib_sod2d/sources/mod_smartredis.f90).

Thank you for offering to help out, I will email you and the support team at BSC so that we can work this out together :)

**Comment by b-fg** [comment]
At the CTE-Power GPU cluster we have finally installed SmartSim and SmartRedis using gcc-8.2.0. However linking to the SmartRedis library and trying to compile code such as
```fortran
module mod_smartredis
   use smartredis_client, only: client_type

   implicit none
   type(client_type) :: client
end module mod_smartredis
```
with the nvidia-hpc compiler yields
```
NVFORTRAN-F-0004-Corrupt or Old Module file /gpfs/projects/bsc21/bsc21850/sod_drl/apps/gpu/smartsim-0.4.2/smartredis/install/include/smartredis_client.mod (/gpfs/projects/bsc21/bsc21850/sod_drl/apps/gpu/relexi_sod/sod2d_gitlab/src/lib_sod2d/sources/mod_smartredis.f90
```

An online search of this error seems to indicate that the nvidia hpc compiler (used to compile the Sod2D library) and the gcc compiler (used to compile SmartRedis) are not compatible, a priori. As @ashao mentioned, compiler flags might be needed to get object names correctly, but I am unsure how to proceed on this front.

@ashao, if you can give me some hints here I can try to look at this before our meeting in Monday. Thank you! :)

**Comment by ashao** [comment]
Let me reach out to folks here within the Cray Programming Environment team to figure out if anyone's done it.
