### ISSUE TITLE
pip install smartsim fails from wrong

### ISSUE THREAD

**Issue by jrwrigh** [CrayLabs/SmartSim#373]
# Description
When trying to run `pip install smartsim` on Python 3.11.2, I get
```
❯ pip install smartsim
Collecting smartsim
  Downloading smartsim-0.4.1.tar.gz (230 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.5/230.5 kB 4.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

# How to reproduce
Run `pip install smartsim`

# System
 - OS: Debian
 - OS version: 12
 - Commit/version of library: N/A
 - Workload manager (e.g. PBS, Slurm): N/A
 - Workload manager version: N/A

**Comment by jrwrigh** [comment]
Looking through the code on GitHub, I can't figure out why this is failing. It's complaining about `extras_require`, which is defined here: https://github.com/CrayLabs/SmartSim/blob/bc7b2323a8a3e9ee9b7b9653e4f843a6a34b5c7a/setup.py#L175-L195

And the `**versions.ml_extras_required()` function is defined here: https://github.com/CrayLabs/SmartSim/blob/bc7b2323a8a3e9ee9b7b9653e4f843a6a34b5c7a/smartsim/_core/_install/buildenv.py#L347-L367

I don't see how this could result in anything that isn't `a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers` other than possibly `ml_extras_required()` returning `{"ml": []}` which technically isn't a list of strings.

Perhaps the fix would be to have `ml_extras_required` returning an empty dictionary if it doesn't have anything?

**Comment by MattToast** [comment]
Hey @jrwrigh! Unfortunately, SmartSim does not have any formal support for Python 3.11.

The reason for exception you are receiving is because 1) SmartSim@0.4.1 was published to PyPI without an upper bound for the `python_requires` as at the time it supported all released versions of Python and 2) the release of `setuptools@67.0.0` introduced a more strict syntax for `pyproject.toml` based projects that requires `extras_requires` strictly be a `dict[str, list[str]]`, not a `dict[str, str | list[str]]`, which is what is present in SmartSim@0.4.1's `setup.py`.

In the meantime, you should be able to install the latest version of SmartSim (v0.5.1) by simply changing your python environment to use Python 3.10! Please feel free to let us know if you run into any other problems with the install process, or if you absolutely must use Python 3.11 and we can try to work something out ASAP!!

**Comment by mellis13** [comment]
We have yanked previous versions of SmartSim that have unbounded ``python_requires``.  This should prevent users from downloading an unintended version and will result in an error being thrown by pip.  Issue #376 will address supporting Python 3.11.  Please feel free to reopen this ticket if we missed something.
